version: '3.8'

services:
  wallet-db:
    image: postgres:15-alpine
    container_name: wallet-db
    environment:
      POSTGRES_DB: walletdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data # <--- 必須加上呢行持久化儲存資料

  redis:
    image: redis:alpine
    container_name: wallet-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: wallet-api
    ports:
      - "8080:8080"
    depends_on:
      - wallet-db
      - redis
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://wallet-db:5432/walletdb
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgrespassword
      SPRING_DATA_REDIS_HOST: redis
      SPRING_DATA_REDIS_PORT: 6379

volumes:
  postgres_data:
